/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Acknowledgement: typeof import('./../components/home/Acknowledgement.vue')['default']
    Additional: typeof import('./../components/home/flows/Additional.vue')['default']
    Banner: typeof import('./../components/home/Banner.vue')['default']
    Basic: typeof import('./../components/home/flows/Basic.vue')['default']
    Custom: typeof import('./../components/home/edges/Custom.vue')['default']
    DocsRepl: typeof import('./../components/DocsRepl.vue')['default']
    Features: typeof import('./../components/home/Features.vue')['default']
    Home: typeof import('./../components/home/Home.vue')['default']
    Input: typeof import('./../components/home/nodes/Input.vue')['default']
    Intro: typeof import('./../components/home/flows/Intro.vue')['default']
    Nested: typeof import('./../components/home/flows/Nested.vue')['default']
    Output: typeof import('./../components/home/nodes/Output.vue')['default']
    Repl: typeof import('./../components/Repl.vue')['default']
    RGB: typeof import('./../components/home/flows/RGB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showcase: typeof import('./../components/home/Showcase.vue')['default']
  }
}

// For TSX support
declare global {
  const Acknowledgement: typeof import('./../components/home/Acknowledgement.vue')['default']
  const Additional: typeof import('./../components/home/flows/Additional.vue')['default']
  const Banner: typeof import('./../components/home/Banner.vue')['default']
  const Basic: typeof import('./../components/home/flows/Basic.vue')['default']
  const Custom: typeof import('./../components/home/edges/Custom.vue')['default']
  const DocsRepl: typeof import('./../components/DocsRepl.vue')['default']
  const Features: typeof import('./../components/home/Features.vue')['default']
  const Home: typeof import('./../components/home/Home.vue')['default']
  const Input: typeof import('./../components/home/nodes/Input.vue')['default']
  const Intro: typeof import('./../components/home/flows/Intro.vue')['default']
  const Nested: typeof import('./../components/home/flows/Nested.vue')['default']
  const Output: typeof import('./../components/home/nodes/Output.vue')['default']
  const Repl: typeof import('./../components/Repl.vue')['default']
  const RGB: typeof import('./../components/home/flows/RGB.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Showcase: typeof import('./../components/home/Showcase.vue')['default']
}