/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Acknowledgement: typeof import('./../components/home/Acknowledgement.vue')['default']
    Additional: typeof import('./../components/home/flows/Additional.vue')['default']
    Banner: typeof import('./../components/home/Banner.vue')['default']
    Basic: typeof import('./../components/home/flows/Basic.vue')['default']
    Custom: typeof import('./../components/home/edges/Custom.vue')['default']
    DocsRepl: typeof import('./../components/DocsRepl.vue')['default']
    Features: typeof import('./../components/home/Features.vue')['default']
    Home: typeof import('./../components/home/Home.vue')['default']
    Input: typeof import('./../components/home/nodes/Input.vue')['default']
    Intro: typeof import('./../components/home/flows/Intro.vue')['default']
    Nested: typeof import('./../components/home/flows/Nested.vue')['default']
    Output: typeof import('./../components/home/nodes/Output.vue')['default']
    Repl: typeof import('./../components/Repl.vue')['default']
    RGB: typeof import('./../components/home/flows/RGB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showcase: typeof import('./../components/home/Showcase.vue')['default']
  }
}
