// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Acknowledgement: typeof import('./../../components/home/Acknowledgement.vue')['default']
    Additional: typeof import('./../../components/home/flows/Additional.vue')['default']
    App: typeof import('./../../components/examples/basic/App.vue')['default']
    Banner: typeof import('./../../components/home/Banner.vue')['default']
    Basic: typeof import('./../../components/home/flows/Basic.vue')['default']
    Controls: typeof import('./../../components/examples/save-restore/Controls.vue')['default']
    Custom: typeof import('./../../components/home/edges/Custom.vue')['default']
    CustomConnectionLine: typeof import('./../../components/examples/connectionline/CustomConnectionLine.vue')['default']
    CustomEdge: typeof import('./../../components/examples/edges/CustomEdge.vue')['default']
    CustomEdge2: typeof import('./../../components/examples/edges/CustomEdge2.vue')['default']
    CustomEdgeLabel: typeof import('./../../components/examples/edges/CustomEdgeLabel.vue')['default']
    CustomInput: typeof import('./../../components/examples/validation/CustomInput.vue')['default']
    CustomNode: typeof import('./../../components/examples/custom-node/CustomNode.vue')['default']
    Features: typeof import('./../../components/home/Features.vue')['default']
    Flow: typeof import('./../../components/examples/multi/Flow.vue')['default']
    Home: typeof import('./../../components/home/Home.vue')['default']
    Input: typeof import('./../../components/home/nodes/Input.vue')['default']
    InteractionControls: typeof import('./../../components/examples/interaction/InteractionControls.vue')['default']
    Intro: typeof import('./../../components/home/flows/Intro.vue')['default']
    Nested: typeof import('./../../components/home/flows/Nested.vue')['default']
    Output: typeof import('./../../components/home/nodes/Output.vue')['default']
    PiniaExample: typeof import('./../../components/examples/pinia/PiniaExample.vue')['default']
    Repl: typeof import('./../../components/Repl.vue')['default']
    RGB: typeof import('./../../components/home/flows/RGB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../../components/examples/dnd/Sidebar.vue')['default']
    TeleportableNode: typeof import('./../../components/examples/teleport/TeleportableNode.vue')['default']
  }
}

export {}
