// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BezierEdge: typeof import('./components/Edges/BezierEdge.vue')['default']
    ConnectionLine: typeof import('./components/ConnectionLine/ConnectionLine.vue')['default']
    DefaultNode: typeof import('./components/Nodes/DefaultNode.vue')['default']
    Edge: typeof import('./components/Edges/Edge.vue')['default']
    EdgeAnchor: typeof import('./components/Edges/EdgeAnchor.vue')['default']
    EdgeText: typeof import('./components/Edges/EdgeText.vue')['default']
    Handle: typeof import('./components/Handle/Handle.vue')['default']
    InputNode: typeof import('./components/Nodes/InputNode.vue')['default']
    Node: typeof import('./components/Nodes/Node.vue')['default']
    NodesSelection: typeof import('./components/NodesSelection/NodesSelection.vue')['default']
    OutputNode: typeof import('./components/Nodes/OutputNode.vue')['default']
    SelectionRect: typeof import('./components/UserSelection/SelectionRect.vue')['default']
    SmoothStepEdge: typeof import('./components/Edges/SmoothStepEdge.vue')['default']
    StepEdge: typeof import('./components/Edges/StepEdge.vue')['default']
    StraightEdge: typeof import('./components/Edges/StraightEdge.vue')['default']
    UserSelection: typeof import('./components/UserSelection/UserSelection.vue')['default']
  }
}

export { }
